### ISSUE TITLE
Suggestion: Travertine brick

### ISSUE THREAD

**Issue by RitterMabuse** [Conquest-Reforged/ConquestReforged#152]
Hello Guys,

first thank you for all your work - the new update is stunning. 
But i have a little issue, i really like the new texture of the Travetine brick - but compared to the old one its way more white, and this messes up some of my builds - is there any possibility that you will change it back or make it look a bit more like the old one?

maybe you can implement the new texture as a whole new block or sth like this?

Bye

**Comment by con-reforged-dev** [comment]
the old traventine will not make a comeback it is unfortunate that your build has suffered due to the change but for the sake of moving forward i suggest replaceing the current traventine blocks with a different material note in the future 1..13 we will be able to add a bunch more different blocks for mover color etc variety so chances that there will be a material that resembles the old traventine while beeing up to quality are higher then
