### ISSUE TITLE
Two texture errors and a annoying bug.

### ISSUE THREAD

**Issue by Lockatz** [Conquest-Reforged/ConquestReforged#173]
When placing rustic wooden beds or big ladders facing north/south ( for big ladders only south) they will display the fancy/straight glass texture instead.
Also, the dirt with cobblestone border doesn´t connect to actual dirt, like it works with the wooden border variant.
Other than that beam walls don´t connect to vertical slabs anymore, like they used to.

Keep your awesome work up !

![2018-05-04_19 33 24](https://user-images.githubusercontent.com/38988448/39642729-e8aeee2c-4fd2-11e8-87d5-5ce72bf30f4c.png)

**Comment by HIPPOKLEIDES** [comment]
I'm afraid these are mainly issues on your end, as this occurs with Optifine is block ids are different in a world from what they are upon starting the game (caused by adding or removing mods that introduce blocks). You might be able to mitigate it by pressing f3+t if you want to keep that world, or you can just start a fresh world after restarting the game
