### ISSUE TITLE
Biome configuration? 

### ISSUE THREAD

**Issue by ano19920** [Conquest-Reforged/ConquestReforged#235]
Are there any config files anywhere for this mod? The situation is that I have selected a specific list of biomes from Biomes O'Plenty and only those biomes are to spawn. However, ConquestReforged seems to be spawning its biomes and there is... no way to stop them? Or at least a config list with options? I want to use both of these mods at the same time, I really do. I just need some options or something. Maybe I'm overlooking it? 

Edit: I am on latest version of CR for minecraft 1.12.2!

**Comment by aaronegger** [comment]
Use this: https://minecraft.curseforge.com/projects/biometweaker
And with the script from here: https://www.reddit.com/r/ConquestReforged/comments/8pbkcq/terrain_generation_options/

noBiomes = forBiomes("conquest:river","conquest:cold_beach_mod","conquest:beach_mod","conquest:oldgrowth_forest","conquest:mountains","conquest:mediterranean","conquest:mesa_extreme_mod","conquest:jungle_mod","conquest:japanese_forest","conquest:red_desert","conquest:desert_mod","conquest:deciduous_forest","conquest:bamboo_forest","conquest:bog","conquest:alder_swamp","conquest:tundra_marsh","conquest:tundra","conquest:lorein_forest","conquest:moorland","conquest:marsh","conquest:forest_flower_plain","conquest:birch_forest","conquest:mega_boreal_forest","conquest:boreal_forest","conquest:ocean")
noBiomes.removeBOP()

Just create a file (to be sure with .cfg ending) and put it into serverfolder/config/BiomeTweaker/scripts.

If the server crashes look at something like this in the output log:
23:38:19 [WARNING] [biometweaker]: Viable generation biomes for type DESERT is empty! This will cause Vanilla generation to crash! You've been warned!
23:38:19 [WARNING] [biometweaker]: Viable generation biomes for type ICY is empty! This will cause Vanilla generation to crash! You've been warned!

This tells you which necessary biome is missing. They prevent the server from generating the world what leads to a crash.

It try to use the mod along with the vanilla world generation, but this is really annoying so far.

I switched to the vanilla world generation, because grinding for ores takes too much time in the conquest world generator.
But it seems that conquest is really aggressive with pushing its own biomes to the world, which breaks the vanilla ore generation which leads to no vanilla ores like gold, iron, diamonds etc are generated.

This is really frustrating.

It is a gread mod, but the fact that there is no configuration makes a bit complicated to use.
I hope i find a workaround that the vanilla biomes are generated. Otherwise i have to remove this mod from my modlist :-1:

**Comment by CreativeRealms** [comment]
Will be fixed in 1.14.
