### ISSUE TITLE
Increasing max stack size

### ISSUE THREAD

**Issue by Spejs** [Conquest-Reforged/ConquestReforged#321]
Even in vanilla it's a pain to have only 64 items per stack and I don't think such limitation adds anything valuable to gameplay. With all the new blocks added this issue would only grow. Why not bump it up to 1024, for example?

**Comment by dags-** [comment]
I don't have an opinion on the gameplay aspect but from a technical point of view this would not really be doable in a clean way for a couple of reasons:

1. Items (where the max stack size is defined) are not modifiable after creation so we can't change the values there.

2. ItemStacks (where the max stack size is used/read) are not extensible so we can't use our own 'modded itemstack' to override the behaviour.

To work around you'd probably have to add some custom nbt data to the ItemStack and track every time it's used to keep your own count of the stack size. Possibly also do some hacky rendering tweaks so that it displays the correct count in the gui too.


All in all I'd say this sort of change lies outside the scope of CR.
I'd be surprised if there wasn't already a mod out there that did this. If it does exist, I wouldn't expect it to be incompatible with CR or anything.

**Comment by Spejs** [comment]
Didn't expect it to have so many issues. Guess I'll look for a separate mod when there is enough content to play survival.
